# Generated by Django 5.1.6 on 2025-03-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_emergencycontact_name_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
